apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: gotocon
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: gotocon
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values: 
                      - gotocon
                topologyKey: "kubernetes.io/hostname"
        containers:
        - name: gotocon
          image: laszlocloud/gotocon
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 1G
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 3
- kind: Service
  apiVersion: v1
  metadata:
    name: gotocon
  spec:
    selector:
      app: gotocon
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
- kind: Ingress
  apiVersion: extensions/v1beta1
  metadata:
    name: gotocon
    annotations:
      # https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md#custom-max-body-size
      ingress.kubernetes.io/proxy-body-size: 8m
      kubernetes.io/ingress.class: "external"
  spec:
    rules:
    - host: gotocon.theselfservicedev.com
      http:
        paths:
        - backend:
            serviceName: gotocon
            servicePort: 8080
